### ISSUE TITLE
An internal server error occured:

### ISSUE THREAD

**Issue by Auggie9010** [SAP-samples/teched2020-DEV165#3]
## Where this problem occurs
[Testing Your Integration Flow](https://github.com/SAP-samples/teched2020-DEV165/blob/main/exercises/Ex-3.Testing_Your_Integration_Scenario.md#testing-your-integration-flow)

7. If the request is successful, you will see a response code 200.

## What is happening
the status is "500 Internal Server Error".
Error is following.

```
An internal server error occured: The MPL ID for the failed message is : AF_SFa7pButNqdPIwkfN6Ck5kBMx
For more details please check tail log.
```

![image](https://user-images.githubusercontent.com/57590680/101773881-b79e3580-3b30-11eb-984a-c0fc98c1e44f.png)

On "Integration Suite>Overview>Monitor Message Processing", following comment is displayed.

![image](https://user-images.githubusercontent.com/57590680/101774109-0055ee80-3b31-11eb-975f-4f0b416a3efc.png)

Could you tell me how I can solve this problem?

**Comment by simplykapoor** [comment]
Hi @Auggie9010 ,

Looks like you have missed a step while designing an integration flow. Kindly check all the steps carefully specially **Step 27** in the given link:

[https://github.com/SAP-samples/teched2020-DEV165/blob/main/exercises/Ex-2.Design_Your_IFlow.md](https://github.com/SAP-samples/teched2020-DEV165/blob/main/exercises/Ex-2.Design_Your_IFlow.md)

Regards,
Sunny

**Comment by Auggie9010** [comment]
Hi @simplykapoor 

Thank you for your comment!
I've check the procedure of **Step27** but the setting seems correct.

![image](https://user-images.githubusercontent.com/57590680/101982943-b8fb6980-3cba-11eb-9706-48f1bf06599b.png)

My entire flow is as follows.
![image](https://user-images.githubusercontent.com/57590680/101982950-c3b5fe80-3cba-11eb-8960-cc813690fe4f.png)

However the same error occurs.

I wonder is there any way to debug the flow just like program to confirm where the procedure stops?

**Comment by simplykapoor** [comment]
Hi @Auggie9010 ,

Can you pease enable the trace and share the trace artifacts?

Regards,
Sunny

**Comment by Auggie9010** [comment]
@simplykapoor 
Thank you for your reply.
Could you possible tell me how to enable the trace and take trace artifacts, please?

**Comment by simplykapoor** [comment]
Inactive thread
