### ISSUE TITLE
Not able to create service key in the BTP Cockpit.

### ISSUE THREAD

**Issue by Sean3350** [SAP-samples/teched2020-DEV165#4]
Hi, 

I've followed the steps to mentioned in the https://github.com/SAP-samples/teched2020-DEV165/blob/main/exercises/create-service-instance-key.md. 

I'm not able proceed further from step 10. I've input the same json body but I got an error message as screenshot in the below. The "Create" button is greyed out. Can you please help me? Thanks. 

![image](https://user-images.githubusercontent.com/95283931/144032941-e8feb2da-1f08-4c08-847e-8f4a98e3359b.png)

Regards,
Sean

**Comment by Sean3350** [comment]
Hi @simplykapoor, 

Can you please help me? Hope to hear from you. Thanks. 

Regards,
Sean

**Comment by simplykapoor** [comment]
Hi @Sean3350,

The flow is changed little bit, you do not need to enter any parameter while creating the service key, it inherits from the service instance.

So you just need to enter the Service Key name and create.

Please check the official help documentation for more details:

[Help Documentation](https://help.sap.com/viewer/368c481cd6954bdfa5d0435479fd4eaf/Cloud/en-US/fd5fcb4f396348e9977b532dbd56a02e.html
)
